version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.25
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-3-223-21-106.compute-1.amazonaws.com
            database: d2lik86ki4i0k9
            ssl: true
            user: pgkbalzbpfzyky
            password: 6b6fed6f3d7f2db6f8f9ddb2360e45ee86ae49ca41ef7cbf022b69cf5396060d
            rawAccess: true
            port: '5432'
            migrations: true
